---
- name: "create web dir"
  file:
    path: ~/web
    state: directory

- name: "copy file to server"
  copy:
    src: artifact.tar.gz
    dest: ~/web

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web

- name: "start server"
  shell: |
    cd ~/web/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
