---
- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "start server"
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
