---
# - name: "copy file to server"
#   copy:
#     src: ~/project/artifact.tar.gz
#     dest: ~/

# - name: Extract foo.tgz into /var/lib/foo
#   unarchive:
#     src: ~/artifact.tar.gz
#     dest: ~/

# - name: "start server"
#   shell: |
#     cd ~/backend
#     npm install
#     pm2 stop default
#     pm2 start npm -- start
- name: creates directory
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: "extract backend artifact."
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople

- name: start server
  shell: |
    cd /home/ubuntu/udapeople
    npm install
    pm2 stop default
    pm2 start npm -- start
