version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
          path: ~/project/frontend
      # - run: cd frontend
      - run:
          name: "install frontend dependencies"
          command: npm install
      - run: npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
          path: ~/project/backend
      # - run: cd backend
      - run: npm install
      - run: npm run build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
